---
# ./install.yml
# currently only installs specified packages
# usage: ansible-playbook install.yml --ask-become-pass
# TODO: * install configuration files
# * install packages from var file.yaml
# * also support debian/arch

- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: "Upgrade all installed packages"
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: "Install from package list"
      become: yes
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ lookup('file', 'bak/pacman-export.txt').splitlines() }}"
