config_version = 14

[bar.default]
background_opacity = 0.75
concave_edge_corners = false

[control_center]
hidden_tabs = [ "weather", "screen-time" ]

[dock]
active_monitor_only = true
background_opacity = 0.0
concave_edge_corners = false
enabled = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@FALLBACK",
    "lockscreen-login-box@luatest",
    "lockscreen-login-box@sunshine",
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@DP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1720.0001220703125
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@luatest"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 665.1851806640625
    output = "luatest"
    placement_height = 800.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@luatest".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@sunshine"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 665.1851806640625
    output = "sunshine"
    placement_height = 800.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@sunshine".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
corner_radius_scale = 2.0

    [shell.panel]
    transparency_mode = "soft"

[theme]
builtin = "Ayu"
community_palette = "Tokyo Night Moon"
custom_palette = "Iceberg"
source = "custom"
wallpaper_scheme = "muted"

    [theme.templates]
    builtin_ids = [ "btop", "kitty" ]
    enable_builtin_templates = true

[wallpaper.default]
path = "/home/mike/Pictures/Wallpapers/fuji_dark.png"

[wallpaper.last]
path = "/home/mike/Pictures/Wallpapers/fuji_dark.png"

[wallpaper.monitors.DP-1]
path = "/home/mike/Pictures/Wallpapers/fuji_dark.png"

[wallpaper.monitors.DP-3]
path = "/home/mike/Pictures/Wallpapers/fuji_dark.png"

[[wallpaper.favorite]]
community_palette = "Catppuccin Macchiato Blue"
palette_source = "community"
path = "/home/mike/Pictures/Wallpapers/fuji_dark.png"
theme_mode = "dark"

[[wallpaper.favorite]]
community_palette = "Tokyo Night Moon"
palette_source = "community"
path = "/home/mike/Pictures/Wallpapers/landscape002.jpg"
theme_mode = "dark"

[widget.clipboard]
enabled = false

[widget.control-center]
enabled = false

[widget.launcher]
enabled = false

[widget.media]
enabled = false

[widget.tray]
drawer = true

[widget.wallpaper]
enabled = false