export PATH=$PATH:/usr/local/go/bin
export PATH="$HOME/.local/bin:$PATH"
# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi
 # AWS (set to mars for duration of internship)
 export AWS_PROFILE='mars'
 # Kops
export KOPS_STATE_STORE='s3://k8s22-state-store'
